repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Isort for import sorting
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        name: 'Sort Python imports with isort'
        language_version: python3.13
        files: \.py$
        exclude: backend/routers/items.py

  # Black for Python code formatting
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.13
        exclude: backend/routers/items.py

  # Prettier for code formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        additional_dependencies: ['prettier@3.3.3']

  # Bandit for Python security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        pass_filenames: false
        args:
          - '-r'
          - '.'
          - '--exclude'
          - './venv/*,./.pytest_cache/*'
          - '-f'
          - 'json' # or "txt", "yaml", "html"
          # - '-o'
          # - 'reports/bandit_report.json'

  # Flake8 for Python linting
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ['--max-line-length=127', '--max-complexity=10']
